import { zcodeProtocolMethods } from "@zcode/shared";

export const UNSUPPORTED_METHODS = new Set<string>([
  zcodeProtocolMethods.pluginsList,
  zcodeProtocolMethods.pluginsReferenceCatalogWithCategory,
  zcodeProtocolMethods.pluginsOverview,
  zcodeProtocolMethods.pluginsMarketplaceAdd,
  zcodeProtocolMethods.pluginsMarketplaceRemove,
  zcodeProtocolMethods.pluginsMarketplaceUpdate,
  zcodeProtocolMethods.pluginsInstall,
  zcodeProtocolMethods.pluginsCancelOperation,
  zcodeProtocolMethods.pluginsUninstall,
  zcodeProtocolMethods.pluginsUpdate,
  zcodeProtocolMethods.pluginsRestoreBuiltin,
  zcodeProtocolMethods.pluginsConfigure,
  zcodeProtocolMethods.pluginsResetConfig,
  zcodeProtocolMethods.pluginsValidate,
  zcodeProtocolMethods.pluginsDescribe,
  zcodeProtocolMethods.pluginsSetEnabled,
  zcodeProtocolMethods.pluginsResolveSuggestedReference,
  zcodeProtocolMethods.workflowsList,
  zcodeProtocolMethods.workflowsGet,
  zcodeProtocolMethods.workflowsUpdateMeta,
  zcodeProtocolMethods.workflowsDelete,
  zcodeProtocolMethods.workflowsRuns,
  zcodeProtocolMethods.workflowsMove,
  zcodeProtocolMethods.workspaceGenerateText,
  zcodeProtocolMethods.workspaceCancelGenerateText,
  zcodeProtocolMethods.providerTestModelConnectivity,
  zcodeProtocolMethods.workspaceHookTrustGrant,
  zcodeProtocolMethods.sessionDebug,
  zcodeProtocolMethods.sessionFork,
  zcodeProtocolMethods.usageStats,
  zcodeProtocolMethods.sessionUsage,
  zcodeProtocolMethods.sessionGoal,
  zcodeProtocolMethods.sessionCancelBackgroundTask,
]);
